from langchain_core.messages import HumanMessage, SystemMessage

STRATEGY_SYSTEM_PROMPT = """You are Astral AI, an expert quantitative trading strategy developer.
When given a natural language request, generate a complete Python trading strategy using Pandas and simple signal logic.
Your code should:
1. Accept a DataFrame with columns: 'open', 'high', 'low', 'close', 'volume'.
2. Return a DataFrame with an additional 'signal' column: 1 for BUY, -1 for SELL, 0 for HOLD.
3. Add a 'position_size_pct' column (0-100) and include basic risk controls when appropriate.
4. Include brief comments explaining the logic.
5. Be ready to pass to a backtesting engine.

Output ONLY the Python code. No markdown fences.
"""

class StrategyGenerator:
    def __init__(self, llm):
        self.llm = llm

    def generate(self, prompt: str) -> str:
        """Generates a Python trading strategy from a natural language prompt."""
        if not self.llm:
            # Return deterministic mock code when no real API key is present
            return self._mock_strategy(prompt)
        
        messages = [
            SystemMessage(content=STRATEGY_SYSTEM_PROMPT),
            HumanMessage(content=f"Create a strategy for: {prompt}")
        ]
        response = self.llm.invoke(messages)
        return self._sanitize_code(response.content)

    def generate_from_graph(self, nodes: list, edges: list) -> str:
        """Generates a strategy from a visual node graph structure."""
        if not self.llm:
            return self._mock_strategy("Visual Strategy Flow")
            
        flow_description = "The user has built a strategy visually with the following nodes:\n"
        for idx, node in enumerate(nodes):
            flow_description += f"- Node {idx} ({node.get('id')}): {node.get('type')}\n"
            
        flow_description += "\nConnections between logic:\n"
        for edge in edges:
            flow_description += f"- Source node {edge.get('source')} -> Target node {edge.get('target')}\n"
            
        flow_description += "\nPlease write a Pandas trading strategy that implements this exact visual flow. Return only the python code block."
        
        messages = [
            SystemMessage(content=STRATEGY_SYSTEM_PROMPT),
            HumanMessage(content=flow_description)
        ]
        response = self.llm.invoke(messages)
        return self._sanitize_code(response.content)

    def _sanitize_code(self, content: str) -> str:
        text = content.strip()
        if text.startswith("```"):
            lines = text.splitlines()
            if len(lines) >= 2:
                lines = lines[1:]
                if lines and lines[-1].strip().startswith("```"):
                    lines = lines[:-1]
            text = "\n".join(lines)
        return text.strip()

    def _mock_strategy(self, prompt: str) -> str:
        return f"""# Strategy: {prompt}
# Generated by Astral AI (Mock Mode - add OpenAI key for real generation)
import pandas as pd

def strategy(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    # --- Indicator Calculation ---
    df['ema_short'] = df['close'].ewm(span=12, adjust=False).mean()
    df['ema_long'] = df['close'].ewm(span=26, adjust=False).mean()
    delta = df['close'].diff()
    gain = delta.where(delta > 0, 0).rolling(14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(14).mean()
    df['rsi'] = 100 - (100 / (1 + gain / loss))

    # --- Signal Logic ---
    df['signal'] = 0
    # BUY when EMA crossover occurs and RSI is not overbought
    df.loc[(df['ema_short'] > df['ema_long']) & (df['rsi'] < 70), 'signal'] = 1
    # SELL when EMA cross under and RSI not oversold
    df.loc[(df['ema_short'] < df['ema_long']) & (df['rsi'] > 30), 'signal'] = -1

    # --- Risk Controls ---
    df['position_size_pct'] = 50
    in_position = False
    cooldown_remaining = 0
    entry_price = 0.0

    for idx in range(len(df)):
        current_price = float(df['close'].iloc[idx])
        raw_signal = int(df['signal'].iloc[idx])

        if cooldown_remaining > 0:
            cooldown_remaining -= 1
            if not in_position:
                df.iloc[idx, df.columns.get_loc('signal')] = 0
                continue

        if in_position:
            stop_level = entry_price * 0.97
            take_level = entry_price * 1.06
            if current_price <= stop_level or current_price >= take_level:
                df.iloc[idx, df.columns.get_loc('signal')] = -1
                in_position = False
                cooldown_remaining = 2
                continue

        if raw_signal == 1 and not in_position:
            entry_price = current_price
            in_position = True
        elif raw_signal == -1 and in_position:
            in_position = False
            cooldown_remaining = 2

    return df
"""
